let URL_REMOTE_API = "http://localhost:9000/";

export default {
    ACTION_AUTH_LOGIN: 'ACTION_AUTH_LOGIN',
    ACTION_AUTH_LOGOUT: 'ACTION_AUTH_LOGOUT',
    ACTION_TOPIC_LIST: 'ACTION_TOPIC_LIST',
    URL_TOPIC_LIST: URL_REMOTE_API + "topic/list",
    URL_USER_LOGIN: URL_REMOTE_API + "user/login"
}