let URL_REMOTE_API = "http://10.16.93.35:3000/";

export default {
    URL_REMOTE_API: URL_REMOTE_API,
    ACTION_AUTH_LOGIN: 'ACTION_AUTH_LOGIN',
    ACTION_AUTH_LOGOUT: 'ACTION_AUTH_LOGOUT',
    ACTION_TOPIC_LIST: 'ACTION_TOPIC_LIST'
}